# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c7165d725e3ad7be19e689a7a151d8774bfced0659095ec151a9fff1a4cd33346ae9f3f9007542b0fa9eb9c6ba76ce507740881db57e17ef398c9338a1ef57
  twitter_secret: P59k8IWy9INwumeD7NHoLIN8QwGIT4Y7jAZX4EQ0xdBbaERezH
  twitter_key: chLEOOXQiN0Y7ovZnNRtynwjk

test:
  secret_key_base: 064d09878b79a5db438096fdab27c4c6fa36ba69e6756ca9fa66bc7be048ec59c8cdbc0523f253a34ee5434146e2415c418de284791cb3e0ef8956c8ab342e94
  twitter_secret: P59k8IWy9INwumeD7NHoLIN8QwGIT4Y7jAZX4EQ0xdBbaERezH
  twitter_key: chLEOOXQiN0Y7ovZnNRtynwjk

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
